### ISSUE TITLE
给大佬递Star，建议放弃论坛那边帖子

### ISSUE THREAD

**Issue by WalterMa** [sffxzzp/Steam-2018-SummerGame#1]
忽略论坛那边帖子的回复，只在GitHub交流可有效过滤低质问题
顺便还能涨一波Star（笑

**Comment by mengshouer** [comment]
同过来给dalao打call。

**Comment by sffxzzp** [comment]
恩。早上那一下真的给气到了。。
之后只在这更新了，虽然好像已经没什么可以更新的了=-=

**Comment by wtfdsy** [comment]
给大佬递star

**Comment by fenguoerbian** [comment]
终于有了github repo~赶紧来给大佬递star~

**Comment by Tyrant107** [comment]
听说大佬已疯，特地做个账号来点star
